// extract-v3.mjs — disassemble banyan-bonsai_v3.html into an importable module.
//
// READ-ONLY on the v3 file: it is the verified engine artifact (10 species, QA'd
// 2026-07-10) and editing it risks exactly the checksum drift the master plan
// warns about. This script slices the engine layers (L0 randomness … L6 scenes,
// everything above the "L7 · app" banner), appends a fixed export list, and
// writes src/engine-v3.gen.js. The app layer (DOM, renderer, panel) stays behind.
//
// The slice is closure-clean by construction (verified 2026-07-10): every engine
// function receives app state (windU / canopyU / soilU / uHor / Qx) as PARAMETERS;
// no engine-layer code references an L7 global. buildFruit self-caches FRUIT_MAT
// at module level, which the slice includes.
//
// Regenerate: node tools/extract-v3.mjs   (build.mjs runs it automatically)
import { readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';

// Parametric since v4: `node tools/extract-v3.mjs [srcHtml] [outJs]`
// defaults extract v3; pass banyan-bonsai_v4.html src/engine-v4.gen.js for v4.
const SRC = process.argv[2] ? pathToFileURL(resolve(process.argv[2])) : new URL('../banyan-bonsai_v3.html', import.meta.url);
const OUT = process.argv[3] ? pathToFileURL(resolve(process.argv[3])) : new URL('../src/engine-v3.gen.js', import.meta.url);

const html = readFileSync(SRC, 'utf8');

// Guard against the FUSE stale-mount truncation (memory.md 2026-07-09/10): a
// short read here would silently ship half an engine.
if (html.length < 150_000) {
  throw new Error(`banyan-bonsai_v3.html read ${html.length} bytes (< 150k) — stale mount? ` +
    `rename-cycle the file (mv x .tmp && mv .tmp x) and retry.`);
}

const mStart = html.indexOf('<script type="module">');
if (mStart < 0) throw new Error('module <script> not found');
const bodyStart = html.indexOf('\n', mStart) + 1;
const appBanner = html.indexOf('/* ================= L7 · app ================= */');
if (appBanner < 0) throw new Error('"L7 · app" banner not found — v3 layout changed; re-map before extracting');
const engine = html.slice(bodyStart, appBanner);

// structural sanity — fail loudly rather than emit a half-engine
for (const marker of [
  "import * as THREE from 'three'",
  'const SPECIES={', 'const QUALITY={', 'function growSkeleton',
  'function buildWood', 'function buildFoliage', 'function buildBlossoms',
  'function makeBarkMaterial', 'function makeLeafMaterial',
  'function makeGroundHeightFn', 'function buildGround', 'const SCENES={',
]) {
  if (!engine.includes(marker)) throw new Error(`extraction sanity failed: missing "${marker}"`);
}
// closure-cleanliness: no engine line may reference an L7-only global.
// (windU/canopyU appear only as parameter names — strip param lists before checking.)
const suspicious = engine.split('\n').filter((l, i) =>
  /\b(document|localStorage|requestAnimationFrame)\b/.test(l));
if (suspicious.length) throw new Error(`engine slice touches DOM:\n${suspicious.join('\n')}`);

const hash = createHash('sha256').update(html).digest('hex').slice(0, 16);
const banner = `// GENERATED by tools/extract-v3.mjs — DO NOT EDIT (edit banyan-bonsai_v3.html, then rebuild).
// Source: banyan-bonsai_v3.html (sha256:${hash}…, ${html.length} bytes), engine layers L0–L6.
// The v3 source file is the verified artifact and is never modified by this pipeline.
`;

const exports = `
/* ---- export surface (appended by extract-v3.mjs) ---- */
export {
  // L0 randomness + math
  mulberry32, reseed, rand, rr, rrOf, ihash01, hashN, vnoise, fbm, lerp, clamp, smoothstep,
  // L1 identity + quality
  SPECIES, QUALITY, resolveQuality,
  // L2 grower
  growSkeleton,
  // L3 mesher
  KIND_ID, computeFrames, tubeGeometry, buttressGeometry, buildWood,
  // L4 foliage instancers
  buildSprigGeometry, buildTuftGeometry, buildFoliage, buildBlossoms, buildFruit,
  // L5 materials
  GUST_GLSL, NOISE_GLSL, makeBarkMaterial, makeLeafMaterial, makeBlossomMaterial,
  // L6 ground + ecology + props + scenes
  makeGroundHeightFn, buildGround, buildLitter, buildGrass, buildPebbles,
  makeStoneMat, PROP_BUILDERS, SCENES, STD_PROPS,
};
${engine.includes('function applyAge')?'export { applyAge };   // v4 stature: age allometry (absent in v3)':''}
${engine.includes('function applySeason')?'export { applySeason, SEASONS, EVERGREEN };   // v4.9 seasons (absent in v3)':''}
`;

writeFileSync(OUT, banner + engine + exports);
console.log(`[extract] ${SRC.pathname.split('/').pop()} → ${OUT.pathname.split('/').pop()} (${(engine.length / 1024).toFixed(0)} KB engine slice, source sha ${hash}…)`);
